import enum
import uuid

from sqlalchemy import String, Enum, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import UUIDPrimaryKeyMixin, TimestampMixin


class ResumeParseStatus(str, enum.Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class Resume(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "resumes"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    file_name: Mapped[str] = mapped_column(String(255), nullable=False)
    storage_path: Mapped[str] = mapped_column(String(1024), nullable=False)  # key/path in storage backend
    file_size_bytes: Mapped[int | None] = mapped_column(nullable=True)
    is_generated: Mapped[bool] = mapped_column(default=False)  # True if generated by our resume builder

    parse_status: Mapped[ResumeParseStatus] = mapped_column(
        Enum(ResumeParseStatus), default=ResumeParseStatus.PENDING, nullable=False
    )
    parse_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Raw structured extraction result (name, skills, education, experience, cgpa, languages, certificates)
    parsed_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    user: Mapped["User"] = relationship("User", back_populates="resumes")
